export type SimpleMarkdownInline = {
  type: "text" | "strong" | "code";
  text: string;
};

export type SimpleMarkdownBlock =
  | {
      type: "heading";
      level: 1 | 2 | 3;
      inlines: SimpleMarkdownInline[];
    }
  | {
      type: "paragraph";
      lines: SimpleMarkdownInline[][];
    }
  | {
      type: "unordered-list" | "ordered-list";
      items: SimpleMarkdownInline[][];
    }
  | {
      type: "quote";
      lines: SimpleMarkdownInline[][];
    }
  | {
      type: "divider";
    };

const INLINE_TOKEN_PATTERN = /(`[^`\n]+`|\*\*[^*\n]+\*\*)/g;
const DIVIDER_PATTERN = /^(?:-{3,}|\*{3,}|_{3,})$/;

export function parseSimpleMarkdownInlines(text: string) {
  const tokens: SimpleMarkdownInline[] = [];
  let cursor = 0;

  for (const match of text.matchAll(INLINE_TOKEN_PATTERN)) {
    const index = match.index ?? 0;
    if (index > cursor) {
      tokens.push({ type: "text", text: text.slice(cursor, index) });
    }
    const value = match[0];
    tokens.push(
      value.startsWith("`")
        ? { type: "code", text: value.slice(1, -1) }
        : { type: "strong", text: value.slice(2, -2) },
    );
    cursor = index + value.length;
  }

  if (cursor < text.length) {
    tokens.push({ type: "text", text: text.slice(cursor) });
  }
  return tokens.length > 0 ? tokens : [{ type: "text" as const, text }];
}

export function parseSimpleMarkdown(content: string): SimpleMarkdownBlock[] {
  const lines = content.replace(/\r\n?/g, "\n").split("\n");
  const blocks: SimpleMarkdownBlock[] = [];
  let paragraphLines: SimpleMarkdownInline[][] = [];
  let list:
    | { type: "unordered-list" | "ordered-list"; items: SimpleMarkdownInline[][] }
    | null = null;
  let quoteLines: SimpleMarkdownInline[][] = [];

  const flushParagraph = () => {
    if (paragraphLines.length > 0) {
      blocks.push({ type: "paragraph", lines: paragraphLines });
      paragraphLines = [];
    }
  };
  const flushList = () => {
    if (list) {
      blocks.push(list);
      list = null;
    }
  };
  const flushQuote = () => {
    if (quoteLines.length > 0) {
      blocks.push({ type: "quote", lines: quoteLines });
      quoteLines = [];
    }
  };
  const flushOpenBlocks = () => {
    flushParagraph();
    flushList();
    flushQuote();
  };

  for (const rawLine of lines) {
    const trimmed = rawLine.trim();
    if (!trimmed) {
      flushOpenBlocks();
      continue;
    }

    if (DIVIDER_PATTERN.test(trimmed)) {
      flushOpenBlocks();
      blocks.push({ type: "divider" });
      continue;
    }

    const heading = trimmed.match(/^(#{1,3})\s+(.+)$/);
    if (heading) {
      flushOpenBlocks();
      blocks.push({
        type: "heading",
        level: heading[1].length as 1 | 2 | 3,
        inlines: parseSimpleMarkdownInlines(heading[2]),
      });
      continue;
    }

    const unorderedItem = rawLine.match(/^\s*[-*+]\s+(.+)$/);
    const orderedItem = rawLine.match(/^\s*\d+[.)]\s+(.+)$/);
    if (unorderedItem || orderedItem) {
      flushParagraph();
      flushQuote();
      const type = unorderedItem ? "unordered-list" : "ordered-list";
      if (
        (list as { type: "unordered-list" | "ordered-list" } | null)?.type !==
        type
      ) {
        flushList();
      }
      list ??= { type, items: [] };
      list.items.push(parseSimpleMarkdownInlines((unorderedItem ?? orderedItem)![1]));
      continue;
    }

    const quote = rawLine.match(/^\s*>\s?(.*)$/);
    if (quote) {
      flushParagraph();
      flushList();
      quoteLines.push(parseSimpleMarkdownInlines(quote[1]));
      continue;
    }

    flushList();
    flushQuote();
    paragraphLines.push(parseSimpleMarkdownInlines(trimmed));
  }

  flushOpenBlocks();
  return blocks;
}

export function stripSimpleMarkdown(content: string) {
  return parseSimpleMarkdown(content)
    .flatMap((block) => {
      if (block.type === "divider") return [];
      if (block.type === "heading") return [block.inlines.map((token) => token.text).join("")];
      const lines = block.type === "paragraph" || block.type === "quote"
        ? block.lines
        : block.items;
      return lines.map((line) => line.map((token) => token.text).join(""));
    })
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

export type ResolvedOptionalTitle = {
  title: string;
  content: string;
  autoGenerated: boolean;
};

/**
 * Uses the first non-empty Markdown line as a title when the explicit title is
 * blank. Multi-line content drops that source line to avoid showing the title
 * twice; a one-line note keeps its original body.
 */
export function resolveOptionalTitle(
  explicitTitle: string,
  sourceContent: string,
  maxTitleLength: number,
): ResolvedOptionalTitle | null {
  const normalizedContent = sourceContent.replace(/\r\n?/g, "\n").trim();
  if (!normalizedContent) return null;

  const normalizedTitle = explicitTitle.trim();
  if (normalizedTitle) {
    return {
      title: normalizedTitle,
      content: normalizedContent,
      autoGenerated: false,
    };
  }

  const lines = normalizedContent.split("\n");
  const firstContentIndex = lines.findIndex((line) => line.trim().length > 0);
  if (firstContentIndex < 0) return null;

  const generatedTitle = stripSimpleMarkdown(lines[firstContentIndex])
    .trim()
    .slice(0, maxTitleLength)
    .trim();
  if (!generatedTitle) return null;

  const remainingLines = lines.slice(firstContentIndex + 1);
  const hasRemainingContent = remainingLines.some(
    (line) => line.trim().length > 0,
  );
  const content = hasRemainingContent
    ? remainingLines.join("\n").replace(/^(?:[ \t]*\n)+/, "").trim()
    : normalizedContent;

  return {
    title: generatedTitle,
    content,
    autoGenerated: true,
  };
}

// Keep the existing helper name for callers that already use it.
export function simpleMarkdownToPlainText(content: string) {
  return stripSimpleMarkdown(content);
}
